version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: battleship
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - 8080:80
    command: ["nginx", "-g", "daemon off;"]
