export const CONST = {};
CONST.AVAILABLE_SHIPS = ['carrier', 'battleship', 'destroyer', 'submarine', 'patrolboat'];

CONST.HUMAN_PLAYER = 0;
CONST.AI_PLAYER = 1;

CONST.CSS_TYPE_EMPTY = 'empty';
CONST.CSS_TYPE_SHIP = 'ship';
CONST.CSS_TYPE_MISS = 'miss';
CONST.CSS_TYPE_HIT = 'hit';
CONST.CSS_TYPE_SUNK = 'sunk';

CONST.TYPE_EMPTY = 0;
CONST.TYPE_SHIP = 1;
CONST.TYPE_MISS = 2;
CONST.TYPE_HIT = 3; 
CONST.TYPE_SUNK = 4;

CONST.DIRECTION_VERTICAL = 0;
CONST.DIRECTION_HORIZONTAL = 1;